### ISSUE TITLE
gmesh - compute-vertex-normals broken?

### ISSUE THREAD

**Issue by timknip** [thi-ng/geom#20]
In cljs this throws "Invalid arity: 0"
```
(defn test-gmesh
  []
  (-> (gmesh)
      (g/add-face [(vec3 0 0 0) (vec3 1 0 0) (vec3 1 1 0)])
      (g/compute-vertex-normals)))
```
Am I missing something here? (like the mesh needing to be a manifold?)

Edit: (gmesh.cljx#243)
```
(transduce ntx g/+ (vec3 0 0 0))
```
Seems to fix the issue.

```
[org.clojure/clojure "1.7.0-beta3"]
[org.clojure/clojurescript "0.0-3291"]
[thi.ng/geom "0.0.783"]

[lein-cljsbuild "1.0.5"]
```

**Comment by postspectacular** [comment]
You're right, of course! `transduce` needs an init value here... and generally I need more tests :) Will fix tonight... Thanks!

**Comment by timknip** [comment]
Gave me the chance to learn a bit on ```transduce``` ;-)
