### ISSUE TITLE
Butterfly subdivision produces faces with nils

### ISSUE THREAD

**Issue by jackrusher** [thi-ng/geom#35]
```
(-> (cuboid 40)
    (g/as-mesh {:mesh (gm/gmesh)})
    sd/butterfly)
```
;;=>
```
{:vertices
 {nil
  #{{:next [0.0 20.0 40.0], :prev [0.0 40.0 40.0], :f [[0.0 40.0 40.0] nil [0.0 20.0 40.0]]}
;; [...]
```

**Comment by postspectacular** [comment]
Butterfly subdivision principally only works with triangle meshes. so please tessellate first - i know, i know... documentation should mention this! :)

Original paper: http://www.math.tau.ac.il/~niradyn/papers/butterfly.pdf

**Comment by postspectacular** [comment]
```
(def m (-> (c/cuboid 80) (g/as-mesh {:mesh (gm/gmesh)})))
(def m2 (last (take 6 (iterate sd/butterfly (g/tessellate m)))))
(with-open [o (io/output-stream "foo.ply")] (mio/write-ply (mio/wrapped-output-stream o) m2))
```
![](http://dev.thi.ng.s3.amazonaws.com/geom/20160301-butterfly.png)

**Comment by postspectacular** [comment]
Proposed fix: Add docstring to point out triangle / pre-tessellation requirement

**Comment by jackrusher** [comment]
Ah, of course! Thanks for the paper.

**Comment by postspectacular** [comment]
Closing this, since it's actually already mentioned :) https://github.com/thi-ng/geom/blob/master/geom-meshops/src/subdivision.org#butterfly
