### ISSUE TITLE
workshop bug: basic 

### ISSUE THREAD

**Issue by verybigelephants** [thi-ng/geom#40]
hey there, this is the bug which we found on the workshop in bratislava

doing `(-> (circle 20) (g/as-polygon 4) (g/extrude {:depth 1}) (g/translate [0 0 10]))` will result in an error

here's the stack				

				IllegalArgumentException No implementation of method: :+ of protocol: #'thi.ng.math.core/IMathOps found for class: java.lang.Double  clojure
				.core/-cache-protocol-fn (core_deftype.clj:568)
				ws-bra-1.core=> *e
				#error {
				 :cause "No implementation of method: :+ of protocol: #'thi.ng.math.core/IMathOps found for class: java.lang.Double"
				 :via
				 [{:type java.lang.IllegalArgumentException
				   :message "No implementation of method: :+ of protocol: #'thi.ng.math.core/IMathOps found for class: java.lang.Double"
				   :at [clojure.core$_cache_protocol_fn invokeStatic "core_deftype.clj" 568]}]
				 :trace
				 [[clojure.core$_cache_protocol_fn invokeStatic "core_deftype.clj" 568]
				  [clojure.core$_cache_protocol_fn invoke "core_deftype.clj" 560]
				  [thi.ng.math.core$eval1449$fn__1450$G__1424__1473 invoke "core.cljc" 8]
				  [thi.ng.geom.basicmesh$eval8466$fn__8507$fn__8508 invoke "basicmesh.cljc" 129]
				  [thi.ng.geom.utils$transform_mesh$fn__7797 invoke "utils.cljc" 426]
				  [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
				  [clojure.core.protocols$fn__6742 invokeStatic "protocols.clj" 75]
				  [clojure.core.protocols$fn__6742 invoke "protocols.clj" 75]
				  [clojure.core.protocols$fn__6684$G__6679__6697 invoke "protocols.clj" 13]
				  [clojure.core$reduce invokeStatic "core.clj" 6545]
				  [clojure.core$reduce invoke "core.clj" 6527]
				  [thi.ng.geom.utils$transform_mesh invokeStatic "utils.cljc" 425]
				  [thi.ng.geom.utils$transform_mesh invoke "utils.cljc" 417]
				  [thi.ng.geom.basicmesh$eval8466$fn__8507 invoke "basicmesh.cljc" 129]
				  [thi.ng.geom.core$eval3115$fn__3116$G__3106__3137 invoke "core.cljc" 43]
				  [ws_bra_1.core$make_rings_along_curve$fn__14626 invoke "core.clj" 59]
				  [clojure.core$map_indexed$mapi__7050$fn__7051 invoke "core.clj" 7022]
				  [clojure.lang.LazySeq sval "LazySeq.java" 40]
				  [clojure.lang.LazySeq seq "LazySeq.java" 49]
				  [clojure.lang.RT seq "RT.java" 521]
				  [clojure.core$seq__4357 invokeStatic "core.clj" 137]
				  [clojure.core$print_sequential invokeStatic "core_print.clj" 46]
				  [clojure.core$fn__6072 invokeStatic "core_print.clj" 153]
				  [clojure.core$fn__6072 invoke "core_print.clj" 153]
				  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
				  [clojure.tools.nrepl.middleware.pr_values$pr_values$fn$reify__614 send "pr_values.clj" 35]
				  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__648$fn__661 invoke "interruptible_eval.clj" 113]
				  [clojure.main$repl$read_eval_print__7408 invoke "main.clj" 241]
				  [clojure.main$repl$fn__7417 invoke "main.clj" 258]
				  [clojure.main$repl invokeStatic "main.clj" 258]
				  [clojure.main$repl doInvoke "main.clj" 174]
				  [clojure.lang.RestFn invoke "RestFn.java" 1523]
				  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__648 invoke "interruptible_eval.clj" 87]
				  [clojure.lang.AFn applyToHelper "AFn.java" 152]
				  [clojure.lang.AFn applyTo "AFn.java" 144]
				  [clojure.core$apply invokeStatic "core.clj" 646]
				  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
				  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
				  [clojure.lang.RestFn invoke "RestFn.java" 425]
				  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
				  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
				  [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__693$fn__696 invoke "interruptible_eval.clj" 222]
				  [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__688 invoke "interruptible_eval.clj" 190]
				  [clojure.lang.AFn run "AFn.java" 22]
				  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
				  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
				  [java.lang.Thread run "Thread.java" 745]]}
				ws-bra-1.core=>
				
				ws-bra-1.core=> (-> (circle 20) (g/as-pol
				g/as-polar     g/as-polygon
				ws-bra-1.core=> (-> (circle 20) (g/as-polygon 4))
				#thi.ng.geom.types.Polygon2{:points [[20.0 0.0] [1.2246467991473533E-15 20.0] [-20.0 2.4492935982947065E-15] [-3.673940397442059E-15 -20.0]]
				}
				ws-bra-1.core=> (require 'ws-bra-1.core :reload)
				
				CompilerException java.lang.IllegalArgumentException: No implementation of method: :+ of protocol: #'thi.ng.math.core/IMathOps found for cla
				ss: java.lang.Double, compiling:(ws_bra_1/core.clj:63:1)
				ws-bra-1.core=> (-> (circle 20) (g/as-polygon 4) (g/extrude)
				g/extrude         g/extrude-shell
				ws-bra-1.core=> (-> (circle 20) (g/as-polygon 4) (g/extrude {:depth 1}))
				#thi.ng.geom.types.BasicMesh{:vertices #{0.0 1.0 20.0 [-3.673940397442059E-15 -20.0 0.0] [-20.0 2.4492935982947065E-15 0.0] [-20.0 2.4492935
				982947065E-15 1.0] [-3.673940397442059E-15 -20.0 1.0] [20.0 0.0 1.0] [1.2246467991473533E-15 20.0 1.0] [20.0 0.0 0.0] [1.2246467991473533E-1
				5 20.0 0.0]}, :faces #{#object[thi.ng.geom.meshface.MeshFace 0x1e1905bf "[[[-20.0 2.4492935982947065E-15 0.0] [-3.673940397442059E-15 -20.0
				0.0] [-3.673940397442059E-15 -20.0 1.0] [-20.0 2.4492935982947065E-15 1.0]]]"] #object[thi.ng.geom.meshface.MeshFace 0x6bfd871b "[[[-3.67394
				0397442059E-15 -20.0 0.0] [20.0 0.0 0.0] [20.0 0.0 1.0] [-3.673940397442059E-15 -20.0 1.0]]]"] #object[thi.ng.geom.meshface.MeshFace 0x762cb
				26f "[[[1.2246467991473533E-15 20.0 0.0] [-20.0 2.4492935982947065E-15 0.0] [-20.0 2.4492935982947065E-15 1.0] [1.2246467991473533E-15 20.0
				1.0]]]"] #object[thi.ng.geom.meshface.MeshFace 0x2657b8ec "[[[20.0 0.0 0.0] [1.2246467991473533E-15 20.0 0.0] [1.2246467991473533E-15 20.0 1
				.0] [20.0 0.0 1.0]]]"] #object[thi.ng.geom.meshface.MeshFace 0x70357564 "[([-3.673940397442059E-15 -20.0 0.0] [-20.0 2.4492935982947065E-15
				0.0] [1.2246467991473533E-15 20.0 0.0] [20.0 0.0 0.0])]"] #object[thi.ng.geom.meshface.MeshFace 0x77f7e126 "[[20.0 0.0 1.0]]"]}, :fnormals {
				}}
				ws-bra-1.core=> (-> (circle 20) (g/as-polygon 4) (g/extrude {:depth 1}) (g/translate [0 0 10]))
				IllegalArgumentException No implementation of method: :+ of protocol: #'thi.ng.math.core/IMathOps found for class: java.lang.Double  clojure
				.core/-cache-protocol-fn (core_deftype.clj:568)

**Comment by postspectacular** [comment]
fixed it, will push new snapshot in a few days

**Comment by verybigelephants** [comment]
@postspectacular hope waking up after the borkovickas and beer was ok by the way!

**Comment by postspectacular** [comment]
yeah! Wed was a deserved soft-holiday for me :) Great to meet you & hope we'll again some time...
