### ISSUE TITLE
colorbar

### ISSUE THREAD

**Issue by rqcy** [thi-ng/geom#45]
Hi,

How to add a colorbar to a heatmap plot?

Thanks!

**Comment by postspectacular** [comment]
You mean like in these diagrams?
![](https://camo.githubusercontent.com/c2cd095d6a47b7f404c0b0e1a8be004af0cb9958/687474703a2f2f6d656469612e7468692e6e672f636f6c6f722f707265736574732f7261696e626f77312e737667)

![](http://thi.ng/img/all-commits.svg)

If so, then pls take a look at the example here:
https://github.com/thi-ng/color/blob/master/src/gradients.org#gradient-presets-visualization

```clojure
(defn color-bars
  [x1 x2 y w h colors]
  (let [n (dec (count colors))]
    (for [i (m/norm-range n)]
      (svg/rect [(m/mix* x1 x2 i) y] w h {:fill (colors (int (* i n)))}))))
```

**Comment by rqcy** [comment]
Yes, thank you!
