### ISSUE TITLE
SVG ellipse and polyline missing

### ISSUE THREAD

**Issue by Sohalt** [thi-ng/geom#54]
Is there a reason the SVG ellipse and polyline primitives are missing?

**Comment by postspectacular** [comment]
@Sohalt the other common name for polylines is `line-strip` and that's available. `ellipse` is missing (sorry), just never needed it so far... but easy enough to add:

```clj
(defn ellipse
  ([p rx ry]
   (ellipse p rx ry nil))
  ([p rx ry attribs]
   [:ellipse
    (svg-attribs
     attribs
     {:cx (*ff* (first p)) :cy (*ff* (nth p 1)) :rx rx : ry})]))
```

**Comment by marco-m** [comment]
@postspectacular it looks like this issue can be closed, right?

**Comment by postspectacular** [comment]
right! :)
