### ISSUE TITLE
MeshFace misses IVertexAccess method

### ISSUE THREAD

**Issue by skrat** [thi-ng/geom#57]
Calling `(g/vertices mf)` raises missing protocol in CLJS. Calling `(g/vertices mf {})` works.

**Comment by postspectacular** [comment]
Thanks @skrat - I merged this yesterday, but there was a minor issue with the two arities. Easy to fix though (https://github.com/thi-ng/geom/commit/e36f9f4ca487037144b6cee126e1598e64c78ba8)
