### ISSUE TITLE
Force Directed Graph layout

### ISSUE THREAD

**Issue by den1k** [thi-ng/geom#64]
https://github.com/thi-ng/geom/blob/master/geom-viz/src/core.org#force-directed-graph-layout

It looks like this project is on pause, but I'm wondering if a graph layout could be in the works.

**Comment by postspectacular** [comment]
Hi @den1k - sorry this *was* in the works, but never more than half-baked and it's unlikely I will continue this. I don't have the code available right now, but I used the geom.physics module to drive the layout...

Also, not directly related, but the only public demo of the physics engine is here:

http://demo.thi.ng/geom/physics/

Maybe that's useful to get going...
