### ISSUE TITLE
Getting error on latest clojurescript

### ISSUE THREAD

**Issue by vushu** [thi-ng/geom#66]
As the title says, I am getting and error when using the latest version of clojurescript 1.10.x 
with thi.ng/geom. When using together with figwheel i get this following error.
```
 ----  Could not Analyze  resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc   line:437  column:41  ----

  Can't recur here at line 437 resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc

  435                          (set! (.-onselectstart canvas) (constantly false))
  436                          (if ctx ctx (recur (next ids))))
  437                        (catch js/Error e (recur (next ids))))))]
                                               ^--- Can't recur here at line 437 resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc
  438          (or ctx (err/unsupported! "WebGL not available"))))))
  439  #?(:clj
  440     (defn clear-color-buffer

----  Analysis Error : Please see resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc  ----
```

I use this version [org.clojure/clojurescript "1.9.89"] to make it work.

**Comment by postspectacular** [comment]
Hey @vushu - thanks for reporting this. Which version of geom are you using. Did you try with the new release candidate `[thi.ng/geom "1.0.0-RC3"]`?

**Comment by vushu** [comment]
Ah thank you, this release works with the latest clojurescript 1.10.339

**Comment by postspectacular** [comment]
Great! Btw. if you want to follow discussion about the upcoming 1.0.0 release, hop onto the #clojure channel on our Discord: https://discord.gg/JhYcmBw
