### ISSUE TITLE
question about drawing 3d objects in worldwind

### ISSUE THREAD

**Issue by zcaudate** [thi-ng/geom#69]
I don't have too much opengl experience but I'm looking to do some visualisations using geom and [worldwind](https://worldwind.arc.nasa.gov/).

I saw that both libraries use org.jogamp.jogl/jogl-all, if that helps integration at all. 

I'm hoping to get some tips on how and where to start.

**Comment by zcaudate** [comment]
okay. I've figured it out.

**Comment by postspectacular** [comment]
Sorry, @zcaudate - been a super busy week and didn't have an answer ready since not familiar w/ Worldwind. Do you have a repo somewhere showing how the integration works? Thanks! :)

**Comment by zcaudate** [comment]
it's still a bit messy and WIP. I'll clean it up first.
