### ISSUE TITLE
how to export step/igs/webgl from Obj?

### ISSUE THREAD

**Issue by selvakarna** [thi-ng/geom#78]
how to export step/igs/webgl from Obj?

**Comment by postspectacular** [comment]
Hi @selvakarna - do you mean converting an OBJ file to Step/IGES? Unfortunately neither of these are directly supported here, but I'm working on an [IGES exporter in TypeScript](https://github.com/thi-ng/umbrella/tree/master/packages/iges). Even that is not a fully automated solution and will still require 1) a 3rd party OBJ parser and 2) step-by-step construction of the result IGES document (iterate over all mesh faces and add each to the doc). Furthermore, that package only supports polygons & polylines right now, but that would be sufficient for OBJ geometry...

**Comment by selvakarna** [comment]
Hi @postspectacular , thanks for reference , can you share , sample code for IGES or STEP export from polylines ?

**Comment by selvakarna** [comment]
How to install this package ? can you share package name and all.

**Comment by postspectacular** [comment]
Hey, as I mentioned, this is not a Clojure project, but a TypeScript package (compiled to JavaScript) and installation details are included in the above linked [readme file](https://github.com/thi-ng/umbrella/blob/master/packages/iges/README.md). You should be able to use this (or other NPM modules) with ClojureScript though: https://clojurescript.org/guides/javascript-modules#node-modules - I have not tried this myself though and can't really help with that...
